Current error:
org.apache.maven.lifecycle.LifecycleExecutionException: Cannot resolve
dependencies of project
org.eclipse.rcptt.module.rap:org.eclipse.rcptt.runtime-updatesite.rap:eclipse-repository:2.6.0-SNAPSHOT
 with context {osgi.os=win32, osgi.ws=win32,
org.eclipse.update.install.features=true, osgi.arch=x86_64,
org.eclipse.update.install.sources=true}
  Software being installed: org.eclipse.rcptt.runtime-updatesite.rap
raw:2.6.0.'SNAPSHOT'/format(n[.n=0;[.n=0;[-S]]]):2.6.0-SNAPSHOT
  Only one of the following can be installed at once:
[org.eclipse.core.runtime 3.15.200.v20190301-1641,
org.eclipse.core.runtime 3.33.0.v20250206-0919]
  Only one of the following can be installed at once:
[org.eclipse.equinox.common 3.10.300.v20190218-2100,
org.eclipse.equinox.common 3.20.0.v20250129-1348]
  Only one of the following can be installed at once:
[org.eclipse.equinox.registry 3.8.300.v20190218-2100,
org.eclipse.equinox.registry 3.12.300.v20250129-1129]
  Cannot satisfy dependency: org.eclipse.equinox.security
1.4.500.v20250129-1350 depends on: java.package;
org.eclipse.core.runtime [3.7.0,4.0.0)
  Cannot satisfy dependency:
org.eclipse.rap.equinox.target.feature.feature.group 3.8.0.20190313-0924
depends on: org.eclipse.equinox.p2.iu; org.eclipse.core.runtime
[3.15.200.v20190301-1641,3.15.200.v20190301-1641]
  Cannot satisfy dependency:
org.eclipse.rap.equinox.target.feature.feature.group 3.8.0.20190313-0924
depends on: org.eclipse.equinox.p2.iu; org.eclipse.equinox.common
[3.10.300.v20190218-2100,3.10.300.v20190218-2100]
  Cannot satisfy dependency:
org.eclipse.rap.equinox.target.feature.feature.group 3.8.0.20190313-0924
depends on: org.eclipse.equinox.p2.iu; org.eclipse.equinox.registry
[3.8.300.v20190218-2100,3.8.300.v20190218-2100]
  Cannot satisfy dependency: org.eclipse.rcptt.runtime-updatesite.rap
raw:2.6.0.'SNAPSHOT'/format(n[.n=0;[.n=0;[-S]]]):2.6.0-SNAPSHOT depends
on: org.eclipse.equinox.p2.iu;
org.eclipse.rcptt.runtime.rap.feature.group 0.0.0
  Cannot satisfy dependency: org.eclipse.rcptt.runtime.rap.feature.group
2.6.0.202502261208 depends on: org.eclipse.equinox.p2.iu;
org.eclipse.equinox.security
[1.4.500.v20250129-1350,1.4.500.v20250129-1350]
  Cannot satisfy dependency: org.eclipse.rcptt.runtime.rap.feature.group
2.6.0.202502261208 depends on: org.eclipse.equinox.p2.iu;
org.eclipse.rap.equinox.target.feature.feature.group
[3.1.0.qualifier,4.0.0), filter=(!(org.eclipse.equinox.p2.exclude.import=true))