Feature based runner (#156)
* Fix "Unable to acquire application service"

IllegalStateException: Unable to acquire application service. Ensure that the org.eclipse.core.runtime bundle is resolved and started (see config.ini).

* Add modules to Runner

* Add mmissing Runner dependencies

* Remove UI dependencies again.

Partially reverts 99fbeeb427b4540292edc60cfa834069b317983f

* Added missing feature